CRITICAL - 2025-04-10 01:19:13 --> ErrorException: unlink(C:\xampp\htdocs\Tesina\writable\debugbar/debugbar_1744241830.022073.json): No such file or directory
[Method: GET, Route: /]
in SYSTEMPATH\Debug\Toolbar\Collectors\History.php on line 82.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'unlink(C:\\xampp\\htdocs\\Tesina\\writable\\debugbar/debugbar_1744241830.022073.json): No such file or directory', 'C:\\xampp\\htdocs\\Tesina\\system\\Debug\\Toolbar\\Collectors\\History.php', 82)
 2 SYSTEMPATH\Debug\Toolbar\Collectors\History.php(82): unlink('C:\\xampp\\htdocs\\Tesina\\writable\\debugbar/debugbar_1744241830.022073.json')
 3 SYSTEMPATH\Debug\Toolbar.php(520): CodeIgniter\Debug\Toolbar\Collectors\History->setFiles('1744258752.266457', 20)
 4 SYSTEMPATH\Debug\Toolbar.php(497): CodeIgniter\Debug\Toolbar->format([...], 'html')
 5 APPPATH\Config\Events.php(47): CodeIgniter\Debug\Toolbar->respond()
 6 SYSTEMPATH\Events\Events.php(155): CodeIgniter\Events\Events::Config\{closure}()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\Events\Events::trigger('pre_system')
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 01:19:13 --> ErrorException: unlink(C:\xampp\htdocs\Tesina\writable\debugbar/debugbar_1744241830.022073.json): No such file or directory
[Method: GET, Route: /]
in SYSTEMPATH\Debug\Toolbar\Collectors\History.php on line 82.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'unlink(C:\\xampp\\htdocs\\Tesina\\writable\\debugbar/debugbar_1744241830.022073.json): No such file or directory', 'C:\\xampp\\htdocs\\Tesina\\system\\Debug\\Toolbar\\Collectors\\History.php', 82)
 2 SYSTEMPATH\Debug\Toolbar\Collectors\History.php(82): unlink('C:\\xampp\\htdocs\\Tesina\\writable\\debugbar/debugbar_1744241830.022073.json')
 3 SYSTEMPATH\Debug\Toolbar.php(520): CodeIgniter\Debug\Toolbar\Collectors\History->setFiles('1744258751.499081', 20)
 4 SYSTEMPATH\Debug\Toolbar.php(497): CodeIgniter\Debug\Toolbar->format([...], 'html')
 5 APPPATH\Config\Events.php(47): CodeIgniter\Debug\Toolbar->respond()
 6 SYSTEMPATH\Events\Events.php(155): CodeIgniter\Events\Events::Config\{closure}()
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\Events\Events::trigger('pre_system')
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-10 09:32:10 --> Intento de inicio de sesión fallido. Email: elvergalarganashe07@gmail.com
ERROR - 2025-04-10 11:34:45 --> Intento de inicio de sesión fallido. Email: brunocameille@alumnos.itr3.edu.ar
ERROR - 2025-04-10 11:37:34 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 11:45:43 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:45:43'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1 in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `invitac...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitac...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitac...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitac...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(1028): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(865): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(251): CodeIgniter\Model->update('5', Array)
#8 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-04-10 11:45:43 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:45:43'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
[Method: POST, Route: admin/guardar-usuario]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 11:45:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:45:43'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:45:43\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:45:43\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 11:45:43 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:45:43'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:45:43\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:45:43\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:45:43\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-10 11:49:07 --> Email ya registrado: balexc777@gmail.com
ERROR - 2025-04-10 11:50:24 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:50:24'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1 in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `invitac...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitac...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitac...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitac...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(1028): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(865): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(251): CodeIgniter\Model->update('5', Array)
#8 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-04-10 11:50:24 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:50:24'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
[Method: POST, Route: admin/guardar-usuario]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 11:50:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:50:24'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:50:24\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:50:24\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 11:50:24 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '2025-04-10 11:50:24'
WHERE `invitaciones`.`id_invitacion` IN ('5')' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:50:24\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:50:24\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `invitaciones` SET `estado` = \'aceptada\',  = \'2025-04-10 11:50:24\'
WHERE `invitaciones`.`id_invitacion` IN (\'5\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `invitaciones` SET `estado` = :estado:,  = ::
WHERE `invitaciones`.`id_invitacion` IN :invitaciones.id_invitacion:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Admin.php(251): CodeIgniter\Model->update('5', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->guardarUsuario()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-10 11:51:07 --> Email ya registrado: balexc777@gmail.com
ERROR - 2025-04-10 11:55:11 --> Invitación no encontrada o inválida
ERROR - 2025-04-10 12:04:18 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:04:23 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:04:39 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:04:54 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:06:05 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:10:59 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:11:16 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:16:28 --> Intento de inicio de sesión fallido. Email: balexc777@gmail.com
ERROR - 2025-04-10 12:17:53 --> Contraseña incorrecta para el usuario: balexc777@gmail.com
ERROR - 2025-04-10 12:20:01 --> Contraseña incorrecta para el usuario: balexc777@gmail.com
ERROR - 2025-04-10 12:21:25 --> Usuario no encontrado: brunocameille@gmail.com
CRITICAL - 2025-04-10 12:26:32 --> Error: Cannot access protected property CodeIgniter\HTTP\IncomingRequest::$uri
[Method: POST, Route: iniciarSesion]
in APPPATH\Controllers\CAutenticacion.php on line 103.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CAutenticacion->iniciarSesion()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CAutenticacion))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-10 12:27:34 --> Usuario no encontrado: tomas@gmail.com
ERROR - 2025-04-10 12:33:11 --> Usuario no encontrado: elvergalarganashe07@gmail.com
ERROR - 2025-04-10 12:33:38 --> Contraseña incorrecta para el usuario: elvergalaranashe07@gmail.com
ERROR - 2025-04-10 12:33:53 --> Contraseña incorrecta para el usuario: elvergalaranashe07@gmail.com
ERROR - 2025-04-10 12:34:07 --> Contraseña incorrecta para el usuario: elvergalaranashe07@gmail.com
ERROR - 2025-04-10 12:41:45 --> Invitación no encontrada o inválida
ERROR - 2025-04-10 12:41:55 --> Contraseña incorrecta para el usuario: balexc777@gmail.com
        CRITICAL - 2025-04-10 22:25:38 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: home/bienvenida]
in APPPATH\Views\home\bienvenida.php on line 113.
 1 APPPATH\Views\home\bienvenida.php(113): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\Tesina\\app\\Views\\home\\bienvenida.php', 113)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\Tesina\\app\\Views\\home\\bienvenida.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home/bienvenida', [], true)
 5 APPPATH\Controllers\Home.php(20): view('home/bienvenida')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->bienvenida()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-10 22:38:24 --> mysqli_sql_exception: Table 'login.energia' doesn't exist in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '1')
#6 C:\xampp\htdocs\Tesina\app\Controllers\Energia.php(103): CodeIgniter\BaseModel->find('1')
#7 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Energia->verDatos('1')
#8 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-04-10 22:38:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.energia' doesn't exist
[Method: GET, Route: energia/verDatos/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
WHERE `energia`.`id` = :energia.id:', [...], false)
 2 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, '1')
 4 APPPATH\Controllers\Energia.php(103): CodeIgniter\BaseModel->find('1')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->verDatos('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 22:38:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.energia' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `energia`
WHERE `energia`.`id` = \'1\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `energia`
WHERE `energia`.`id` = \'1\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
WHERE `energia`.`id` = :energia.id:', [...], false)
 4 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, '1')
 6 APPPATH\Controllers\Energia.php(103): CodeIgniter\BaseModel->find('1')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->verDatos('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 22:38:24 --> [Caused by] mysqli_sql_exception: Table 'login.energia' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *
FROM `energia`
WHERE `energia`.`id` = \'1\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `energia`
WHERE `energia`.`id` = \'1\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `energia`
WHERE `energia`.`id` = \'1\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
WHERE `energia`.`id` = :energia.id:', [...], false)
 5 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, '1')
 7 APPPATH\Controllers\Energia.php(103): CodeIgniter\BaseModel->find('1')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->verDatos('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 22:48:51 --> ErrorException: Declaration of App\Models\DispositivoModel::findAll(int $limit = 0, int $offset = 0) must be compatible with CodeIgniter\BaseModel::findAll(?int $limit = null, int $offset = 0)
[Method: GET, Route: dispositivo]
in APPPATH\Models\DispositivoModel.php on line 73.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-04-10 22:48:53 --> ErrorException: Declaration of App\Models\DispositivoModel::findAll(int $limit = 0, int $offset = 0) must be compatible with CodeIgniter\BaseModel::findAll(?int $limit = null, int $offset = 0)
[Method: GET, Route: dispositivo]
in APPPATH\Models\DispositivoModel.php on line 73.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-04-10 22:48:57 --> ErrorException: Declaration of App\Models\DispositivoModel::findAll(int $limit = 0, int $offset = 0) must be compatible with CodeIgniter\BaseModel::findAll(?int $limit = null, int $offset = 0)
[Method: GET, Route: dispositivo]
in APPPATH\Models\DispositivoModel.php on line 73.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-04-10 22:51:42 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: energia]
in APPPATH\Views\consumo.php on line 154.
 1 APPPATH\Views\consumo.php(154): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\Tesina\\app\\Views\\consumo.php', 154)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\Tesina\\app\\Views\\consumo.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('consumo', [], true)
 5 APPPATH\Controllers\Energia.php(90): view('consumo', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-10 22:52:20 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: energia]
in APPPATH\Views\consumo.php on line 154.
 1 APPPATH\Views\consumo.php(154): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\Tesina\\app\\Views\\consumo.php', 154)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\Tesina\\app\\Views\\consumo.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('consumo', [], true)
 5 APPPATH\Controllers\Energia.php(90): view('consumo', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
